"""empty message

Revision ID: 4af233a6bf7b
Revises: 5b5afdf142ad
Create Date: 2022-11-25 09:43:31.515431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af233a6bf7b'
down_revision = '5b5afdf142ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'typeOfTicket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('typeOfTicket', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
