"""empty message

Revision ID: 5b5afdf142ad
Revises: 24dfd5588d18
Create Date: 2022-11-25 09:41:56.705794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5afdf142ad'
down_revision = '24dfd5588d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'typeOfTicket')
    op.add_column('ticket', sa.Column('typeOfTickets', sa.String(), nullable=True))
    op.drop_column('ticket', 'typeOfTicket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('typeOfTicket', sa.VARCHAR(), nullable=True))
    op.drop_column('ticket', 'typeOfTickets')
    op.add_column('customer', sa.Column('typeOfTicket', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
