"""empty message

Revision ID: 7998c55358e2
Revises: ebd13cf9dcf5
Create Date: 2022-11-17 01:40:17.842932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7998c55358e2'
down_revision = 'ebd13cf9dcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'talanku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('talanku', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
