"""empty message

Revision ID: 8640671ea6af
Revises: be40265e7bc9
Create Date: 2022-11-25 09:46:21.382189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8640671ea6af'
down_revision = 'be40265e7bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'typeOfTickets')
    op.add_column('ticket', sa.Column('typeOfTickets', sa.String(), nullable=True))
    op.drop_column('ticket', 'typeOfTicket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('typeOfTicket', sa.VARCHAR(), nullable=True))
    op.drop_column('ticket', 'typeOfTickets')
    op.add_column('customer', sa.Column('typeOfTickets', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
