"""empty message

Revision ID: 939a5c73f660
Revises: cf88bebd42e8
Create Date: 2022-10-25 15:22:53.837816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939a5c73f660'
down_revision = 'cf88bebd42e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate', sa.String(), nullable=False),
    sa.Column('candidateName', sa.String(), nullable=True),
    sa.Column('award', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
