"""empty message

Revision ID: a367f4c31fc7
Revises: ed20e2197b93
Create Date: 2022-11-25 08:25:00.814350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a367f4c31fc7'
down_revision = 'ed20e2197b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'code')
    # ### end Alembic commands ###
