"""empty message

Revision ID: be40265e7bc9
Revises: 9e75cf767ac9
Create Date: 2022-11-25 09:45:41.767021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be40265e7bc9'
down_revision = '9e75cf767ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'typeOfTicket')
    op.add_column('ticket', sa.Column('typeOfTickets', sa.String(), nullable=True))
    op.drop_column('ticket', 'typeOfTicket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('typeOfTicket', sa.VARCHAR(), nullable=True))
    op.drop_column('ticket', 'typeOfTickets')
    op.add_column('customer', sa.Column('typeOfTicket', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
