"""empty message

Revision ID: c3dee3edf39b
Revises: e08ef5f67424
Create Date: 2022-11-17 01:43:14.196994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dee3edf39b'
down_revision = 'e08ef5f67424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('tlk', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'tlk')
    # ### end Alembic commands ###
