"""empty message

Revision ID: cd03cbfbe865
Revises: 8640671ea6af
Create Date: 2022-11-27 15:26:49.980245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd03cbfbe865'
down_revision = '8640671ea6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('customerName', sa.String(), nullable=True),
    sa.Column('typeOfTicket', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_transaction')
    # ### end Alembic commands ###
