"""empty message

Revision ID: ebd13cf9dcf5
Revises: 939a5c73f660
Create Date: 2022-11-16 17:49:25.288864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd13cf9dcf5'
down_revision = '939a5c73f660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('movie', sa.String(), nullable=True),
    sa.Column('movieConfirm', sa.String(), nullable=True),
    sa.Column('talanku', sa.Boolean(), nullable=True),
    sa.Column('probability', sa.String(), nullable=True),
    sa.Column('startDate', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll')
    # ### end Alembic commands ###
