"""empty message

Revision ID: ed20e2197b93
Revises: 0c626aebd216
Create Date: 2022-11-25 08:12:22.295612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed20e2197b93'
down_revision = '0c626aebd216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ussd_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ussd_sessions')
    # ### end Alembic commands ###
